name: Build Debian Package

on:
  push:
    branches:
      - main  # Anpassen, wenn Ihre Hauptbranch einen anderen Namen hat

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker
      uses: actions/setup-docker@v2
      
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev
        
    - name: Build Debian Package
      run: |
        mkdir build
        cp -r DEBIAN/* build/DEBIAN/
        cp -r usr/* build/usr/
        cp -r etc/* build/etc/
        dpkg-deb --build build/
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: debian-package
        path: "*.deb"
