name: Build Debian Package

on:
  push:
    branches:
      - main  # Anpassen, wenn der Standardbranch abweicht

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y dpkg-dev
      
    - name: Build Debian package
      run: dpkg-deb --build .
      
    - name: Move package to artifacts
      run: mv *.deb /github/workspace
      
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: debian-package
        path: ./*.deb
